version: '3.7'
services:
  django:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/django
    command: bash -c 'python manage.py migrate; python manage.py loaddata fixtures/data.json; python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.develop

  aiogram:
    container_name: bot
    build:
      context: telegram_bot
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://django:8000/
    env_file:
      - telegram_bot/.env
    depends_on:
      - django